version: '3.8'
services:
  redis:
    image: redis
    command: /bin/sh -c "redis-server --requirepass 'password'"
    ports:
      - 6379:6379
    expose:
      - 6379
#  db:
#    image: postgres
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: phone_number_db