micronaut:
  application:
    name: phone_number_parser
redis:
  uri: redis://localhost:6379

#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/phone_number_db
#    driverClassName: org.postgresql.Driver
#    username: root
#    password: password
#flyway:
#  datasources:
#    default:
#      enabled: true
#      clean-schema: true
#endpoints:
#  flyway:
#    sensitive: false